!function(e){var n={};function t(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:r})},t.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},t.t=function(e,n){if(1&n&&(e=t(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(t.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var o in e)t.d(r,o,function(n){return e[n]}.bind(null,o));return r},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},t.p="",t(t.s="./src/js/main.js")}({"./src/js/form.js":
/*!************************!*\
  !*** ./src/js/form.js ***!
  \************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nvar sendingForm = function sendingForm() {\n  var form = document.querySelector('.form');\n  var link = document.querySelector('.link');\n  var formButton = document.querySelector('.form__button');\n  var surname = document.querySelector('input[name=\"surname\"]');\n\n  var clickBtn = function clickBtn() {\n    if (surname.value == '') {} else {\n      form.classList.add('form__click');\n      link.classList.add('link__click');\n    }\n  };\n\n  formButton.addEventListener('click', clickBtn);\n};\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (sendingForm);\n\n//# sourceURL=webpack:///./src/js/form.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _form__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./form */ "./src/js/form.js");\n/* harmony import */ var _timer__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./timer */ "./src/js/timer.js");\n\n\nwindow.addEventListener(\'DOMContentLoaded\', function () {\n  Object(_form__WEBPACK_IMPORTED_MODULE_0__["default"])(); // startTimer();\n});\n\n//# sourceURL=webpack:///./src/js/main.js?')},"./src/js/timer.js":
/*!*************************!*\
  !*** ./src/js/timer.js ***!
  \*************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nvar startTimer = function startTimer(duration, display) {\n  var timerText = document.querySelector('.timer__text');\n  var btn = document.querySelector('.link__button');\n  var link = document.querySelector('.link');\n  var authorization = document.querySelector('.authorization');\n  var timer = duration,\n      minutes,\n      seconds;\n  setInterval(function () {\n    minutes = parseInt(timer / 60, 10);\n    seconds = parseInt(timer % 60, 10);\n    minutes = minutes < 10 ? \"0\" + minutes : minutes;\n    seconds = seconds < 10 ? \"0\" + seconds : seconds;\n    display.textContent = minutes + \":\" + seconds;\n\n    if (--timer < 0) {\n      timer = 0;\n      timerText.classList.add('timer__none');\n      btn.classList.add('button__block');\n    }\n  }, 1000);\n  btn.addEventListener('click', function () {\n    link.classList.add('link__none');\n    authorization.classList.add('authorization__block');\n  });\n};\n\nwindow.onload = function () {\n  var fiveMinutes = 25,\n      display = document.querySelector('#time');\n  startTimer(fiveMinutes, display);\n};\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (startTimer);\n\n//# sourceURL=webpack:///./src/js/timer.js?")}});
//# sourceMappingURL=main.js.map
